version: "3.9"
services:
  container-frontend:
    container_name: container-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    networks:
      - networkDocker
      
networks:
  networkDocker:
