version: "3.9"
services:
  container-jenkins:
    container_name: container-jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - networkDocker

volumes:
  jenkins_home:

networks:
  networkDocker:
