version: "3.9"
services:
  container-backend:
    container_name: container-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - networkDocker
    volumes:
      - ./src/uploads:/home/app/uploads

networks:
  networkDocker:
